### ISSUE TITLE
Availability for Apple silicon chip

### ISSUE THREAD

**Issue by Juke34** [conda-forge/perl-clone-feedstock#1]
### Comment:

Is terre any reason why this perl module (as some others) is not available for apple silicon chip, while some other perl module are (e.g. perl-clone-choose)?
I would be grateful you can make it available.

I would be ready to help (I'm part of bioconda but the recipe has moved here since last year...).

**Comment by xileF1337** [comment]
Hi, sorry for the late reply. I assume the varying support for your platform is a result of the fact that some Perl packages are labelled as "noarch" packages, meaning that they can run on any platform, while other packages require platform-specific (compiled) code. If CondaForge builds are not available for your platform, you are not able to use such a package. 

Unfortunately, this module requires compiled code and is thus not portable. You can check whether a Perl package requires compiled code by looking at the requirements in the recipe's `meta.yaml` file. If you see a line like [{{ compiler('c') }}](https://github.com/conda-forge/perl-clone-feedstock/blob/9e63adcc03d9a78d222a6b565d700b6a71f1ec95/recipe/meta.yaml#L23), it means the recipe requires compiled code. If you do *not* see such a line, it is possible the recipe is lacking a [`noarch: generic` entry](https://github.com/conda-forge/perl-clone-choose-feedstock/blob/62b4983b18a157b60dcfc7ad764fb79b4ebcf6d0/recipe/meta.yaml#L14). In this case, feel free to open an issue and ask the author to add it.

I am sorry I cannot do more to help you. I am closing this issue now.

**Comment by Juke34** [comment]
Is it planned to add the arm64 platform at some point?

**Comment by xileF1337** [comment]
I have no idea, you would have to ask the core team I guess. I am just a recipe author, I am not involved in such things. Since another target platform would require lots of resources (persons and hardware), I assume it is not going to happen unless someone is investing these resources into the project. But asking won't cost you anything, I guess ;⁠)

**Comment by Juke34** [comment]
Any update on this?
